services:
  pubsub-emulator:
    container_name: pubsub-emulator
    build:
      context: ./pubsub
      dockerfile: Dockerfile
    restart: always
    platform: linux/amd64
    environment:
      - PUBSUB_PROJECT_ID=my-project
      - PUBSUB_TOPIC_ID=my-topic
      - PUBSUB_SUBSCRIPTION_ID=my-subscription
      - PUBSUB_EMULATOR_HOST=0.0.0.0:8085
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - .:/code
    command: 
      ./pubsub/entrypoint.sh
    ports:
      - 8085:8085
  publisher:
    container_name: publisher
    build:
      context: ./publisher
      dockerfile: Dockerfile
    env_file:
      - ./publisher/.env.dev
    command: sleep infinity
    ports:
      - 8080:8080
    volumes:
      - ./publisher:/app
  subscriber:
    container_name: subscriber
    build:
      context: ./subscriber
      dockerfile: Dockerfile
    env_file:
      - ./subscriber/.env.dev
    working_dir: /app
    command: sleep infinity
    volumes:
      - ./subscriber:/app
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    depends_on:
      - publisher
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    env_file:
      - ./ngrok/.env
    volumes:
      - ./ngrok/ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040


